version: "3.5"

services:
  konga:
    image: pantsel/konga:latest
    ports:
      - '1337:1337'
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  kong-migrations-up:
    image: kong:3.0
    #command: kong migrations bootstrap
    command: kong migrations up
    environment:
      KONG_PG_HOST: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PG_PORT: 5432
    restart: on-failure


  postgres:
    image: bitnami/pgbouncer:1-debian-11
    ports:
      - '6432:6432'
    secrets:
      - KONG_DB_PW
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: kong
      POSTGRESQL_USERNAME: kong
      POSTGRESQL_PASSWORD_FILE: /run/secrets/KONG_DB_PW
      PGBOUNCER_BIND_ADDRESS: 0.0.0.0
      PGBOUNCER_PORT: 6432
    networks:
      default:
        ipv4_address: 172.28.5.251

  db:
    image: bitnami/postgresql:14-debian-11
    ports:
      - '5432:5432'
    restart: always
    secrets:
      - POSTGRESQL_PASSWORD
      - K3D_DB_PW
      - KONG_DB_PW
      - HARBOR_DB_PW
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD_FILE: /run/secrets/POSTGRESQL_PASSWORD
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./.pg/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    networks:
      default:
        ipv4_address: 172.28.5.250

volumes:
  postgresql_data:

secrets:
  POSTGRESQL_PASSWORD:
    file: ./.pg/root_passwd.secret
  K3D_DB_PW:
    file: ./.pg/k3d_passwd.secret
  KONG_DB_PW:
    file: ./.pg/kong_passwd.secret
  HARBOR_DB_PW:
    file: ./.pg/harbor_passwd.secret

networks:
  default:
    name: k3d
    external: true
