version: "3.5"

services:
  db:
    image: cr.hvg.hu/hub/bitnami/postgresql:14-debian-11
    ports:
      - '5432:5432'
    restart: always
    secrets:
      - POSTGRES_PW
      - K3D_DB_PW
      - KONG_DB_PW
      - HARBOR_DB_PW
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD_FILE: /run/secrets/POSTGRES_PW
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./.pg/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    networks:
      default:
        ipv4_address: 172.28.255.254

volumes:
  postgresql_data:

secrets:
  POSTGRES_PW:
    file: ./.pg/root_passwd.secret
  K3D_DB_PW:
    file: ./.pg/k3d_passwd.secret
  KONG_DB_PW:
    file: ./.pg/kong_passwd.secret
  HARBOR_DB_PW:
    file: ./.pg/harbor_passwd.secret

networks:
  default:
    name: k3d
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/16
        gateway: 172.28.0.1
        ip_range: 172.28.1.0/24
