version: '3.5'

services:

  dev:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      default:
        ipv4_address: 172.28.254.254
    build:
      args:
        VARIANT: bullseye
        KUBE_CTL_VERSION: v1.28.2
        K9S_VERSION: v0.27.4
      context: ./.devcontainer
      dockerfile: Dockerfile
    environment:
      KUBECONFIG: /workspace/.kube/config
    volumes:
      - .:/workspace:cached
    command:
    - /bin/sh
    - -c
    - 'while sleep 1000; do :; done'
